require("lconfig.base")
require("lconfig.colors")
require("lconfig.indent")
require("lconfig.search")
require("lconfig.filetypes")
require("lconfig.terminal")

require("lconfig.plugins")
require("lconfig.plugins.luasnip")
require("lconfig.plugins.cmp").config()
require("lconfig.plugins.lspconfig").config()
require("lconfig.plugins.treesitter").config()
require("lconfig.plugins.telescope").config()
require("lconfig.plugins.dadbod")
require("lconfig.plugins.gitsigns").config()
require("lconfig.plugins.nvim-tree").config()
