vim.cmd("augroup FileTypeCheck")
vim.cmd("autocmd!")
vim.cmd("autocmd BufNewFile,BufRead *.x set filetype=alex")
vim.cmd("autocmd BufNewFile,BufRead *.y set filetype=happy")
vim.cmd("autocmd BufNewFile,BufRead *.html set filetype=htmljinja.html")
vim.cmd("autocmd BufNewFile,BufRead *.j2 set filetype=jinja")
vim.cmd("autocmd BufNewFile,BufRead *.jinja set filetype=jinja")
vim.cmd("autocmd BufNewFile,BufRead *.hbs set filetype=html")
vim.cmd("autocmd BufNewFile,BufRead *.handlebars set filetype=html")
vim.cmd("autocmd BufNewFile,BufRead Vagrantfile set filetype=ruby")
vim.cmd("autocmd BufNewFile,BufRead Jenkinsfile set filetype=groovy")
vim.cmd("autocmd BufNewFile,BufRead *.sql set filetype=pgsql")
vim.cmd("autocmd BufNewFile,BufRead *.pyi set filetype=python")
vim.cmd("autocmd BufNewFile,BufRead *.cassandra set filetype=cql")
vim.cmd("autocmd BufNewFile,BufRead build.boot set filetype=clojure")
vim.cmd("autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx")
vim.cmd("autocmd BufNewFile,BufRead *.fnl set filetype=fennel")
vim.cmd("augroup END")
